/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 Newdrone.gltf
Author: shinieater (https://sketchfab.com/Dang_Jimmy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/drone-jimmy-dang-25fe9c42f0f446bf95ef9594cccf9610
Title: Drone - Jimmy Dang
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Newdrone.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lid_Frame_Transparent_0.geometry} material={materials.Transparent} position={[0, 0, -0.125]} />
      <mesh geometry={nodes.Main_Body_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.Top_Frame_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.Camera_lambert1_0.geometry} material={materials.lambert1} position={[0, -0.337, 0.862]} scale={[0.244, 0.228, 0.208]} />
      <group position={[0.007, 0, -0.002]}>
        <mesh geometry={nodes.polySurface1_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface2_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface3_lambert1_0.geometry} material={materials.lambert1} />
      </group>
      <group position={[-1.95, -0.006, -1.734]} rotation={[-Math.PI, -0.266, -Math.PI]} scale={[1, 0.847, 1]}>
        <mesh geometry={nodes.polySurface4_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface5_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface6_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface7_lambert1_0.geometry} material={materials.lambert1} />
      </group>
      <mesh geometry={nodes.Wing_Arm_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.Wing_Arm_Handle_lambert1_0.geometry} material={materials.lambert1} position={[-0.258, -0.25, -0.981]} rotation={[Math.PI / 2, 0, 0.63]} scale={[0.054, 0.108, 0.054]} />
      <mesh geometry={nodes.Wing_Stand_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.Wing_lambert1_0.geometry} material={materials.lambert1} position={[0.381, -0.006, -0.293]} rotation={[0, 0.283, 0]} scale={[1, 0.847, 1]} />
      <mesh geometry={nodes.FWing_Arm_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.Front_Stand_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pTorus1_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/Newdrone.gltf')
